<?php
require_once '../../../includes/db.php';

$id = $_GET['id'] ?? null;
$type = $_GET['type'] ?? null;

if (!$id || !$type) {
    die('Invalid or missing parameters.');
}

if ($type === 'operational') {
    $stmt = $pdo->prepare("
        SELECT oe.particular as expense_name, oe.amount,
               r.id AS receipt_id, r.receipt_no, r.date_issued
        FROM operational_expenses oe
        LEFT JOIN receipts r ON r.expense_id = oe.id
        WHERE oe.id = :id
    ");
} elseif ($type === 'compliance') {
    $stmt = $pdo->prepare("
        SELECT ce.type as expense_name, ce.amount,
               r.id AS receipt_id, r.receipt_no, r.date_issued
        FROM compliance_expenses ce
        LEFT JOIN receipts r ON r.compliance_id = ce.id
        WHERE ce.id = :id
    ");
} else {
    die('Invalid receipt type.');
}

$stmt->execute([':id' => $id]);
$receipt = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$receipt) {
    die('Receipt not found.');
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Receipt <?= htmlspecialchars($receipt['receipt_no'] ?? 'N/A') ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="icon" href="../../../logo.png" type="image/png">
    <style>
        @media print {
            .no-print {
                display: none !important;
            }
        }
    </style>
</head>
<body class="p-5 bg-light">
    <div class="card mx-auto" style="max-width:600px;">
        <div class="card-body">
            <h4 class="text-center mb-3">Official Receipt</h4>
            <hr>
            <p><strong>Receipt No:</strong> <?= htmlspecialchars($receipt['receipt_no'] ?? 'N/A') ?></p>
            <p><strong>Date Issued:</strong> <?= htmlspecialchars($receipt['date_issued'] ?? 'N/A') ?></p>
            <p><strong>Category:</strong> <?= ucfirst(htmlspecialchars($type)) ?></p>
            <p><strong>Description:</strong> <?= htmlspecialchars($receipt['expense_name'] ?? 'N/A') ?></p>
            <p><strong>Amount:</strong> ₱<?= number_format($receipt['amount'] ?? 0, 2) ?></p>
            <hr>
            <p class="text-center small text-muted">Generated by System Auto-Billing</p>
            <div class="text-center no-print">
                <button onclick="window.print()" class="btn btn-primary">Print / Save PDF</button>
            </div>
        </div>
    </div>
</body>
</html>
